### ISSUE TITLE
Cannot open plugin menu after update to 4.0.0

### ISSUE THREAD

**Issue by ma-tongji** [modheader/modheader#115]
I never update my chrome extensions, but now the version shows 4.0.0, maybe it automatically do an update.

Problem is that I cannot open the menu now when clicking the modheader tool icon. Do you have any idea why this happen? I guess I'd better do some backups and re-install the extension

**Comment by hao1300** [comment]
@ma-tongji - I have gotten some similar reports from other users. Some users are able to recover by going to chrome://extensions, then turn off and turn on ModHeader again. Please check if this works for you.

Also, what is your browser version? I have gotten some reports from users with older browsers. If your browser version is too old, can you try upgrading?

I have created a fix for both of these issues, but unfortunately it needs to go through Chrome Web Store approval before releasing, which can take anywhere from a day to a few weeks. If neither workarounds solve your problem, can you go to **chrome://extensions**, enable **Developer mode**, then click on **Background page** for ModHeader and check if there are any error there?

**Comment by ma-tongji** [comment]
@hao1300 

Thanks for the reply. Turn off and turn on ModHeader didn't work for me. My Chrome version is 75.0.3770.142, I'm not going to upgrade my browser if there are any solution.

Below is the error message when I click on Background page for ModHeader
![](https://i.ibb.co/2NX6yKM/123.jpg)

**Comment by hao1300** [comment]
@ma-tongji 

I have a bug in the newer version that relies on some newer JS syntax that is not available in the older browser. I have submitted a fix for older browsers, but it is still waiting for Chrome Web Store review. It is taking longer than usual. Sadly I don't have control over this. Hopefully they will approve and publish the fix soon (maybe in a day or two)

That said, your browser version is 3 years old. It will be hard for me to guarantee ModHeader can continue to work on such old browser versions going forward, especially since Chrome Web Store is forcing all extensions to upgrade to the newer extension API by the end of this year (https://developer.chrome.com/docs/extensions/mv3/intro/). I can continue to support older browsers for a few more months, but sooner or later I will need to break compatibility or ModHeader may get removed from the Chrome Web Store.

**Comment by ma-tongji** [comment]
@hao1300 

I see. I re-installed the old version (3.1.27) from Developer mode manually and it works for now anyway.

**Comment by hao1300** [comment]
Note: you can download the archived version of ModHeader here: https://github.com/modheader/modheader/releases/tag/v3.1.27
