### ISSUE TITLE
ModHeader 4.0.4 still not working in FF68

### ISSUE THREAD

**Issue by jockie** [modheader/modheader#116]
I'm using portable FF68.10.0esr in a project because the customers are currently pinned to that exact version.

Since updating to 4.0.0 the ModHeader flyout does not show at all:
![grafik](https://user-images.githubusercontent.com/6338005/168240140-eca2fd18-3b09-4834-aae0-35c9b502c9ed.png)

Today I've updated to 4.0.4 because the changelogs states that it would support FF68, but still the same UI behaviour.

Addon debugging console shows error:
![grafik](https://user-images.githubusercontent.com/6338005/168239787-dcd5a8c6-8589-43eb-9c9c-29ba4ec776b7.png)

Sorry for only having the German console message at hand:
`Sicherheitsfehler: Inhalt auf moz-nullprincipal:{2d65eb2e-db38-4468-8aa2-6560fff992fe} darf keine Daten von moz-extension://1ea1f151-47ff-46b0-a783-879b4499ed85/js/background.js laden.
Sicherheitsfehler: Inhalt auf moz-nullprincipal:{a3f354b9-9fbe-45e8-93c1-3eb4c7d75da9} darf keine Daten von moz-extension://1ea1f151-47ff-46b0-a783-879b4499ed85/js/background.js laden.`

**Comment by hao1300** [comment]
I updated v4.0.4 to support an older version of the Chrome from 2 years ago, but FF68 is from 3 years ago.

I think the issue is that I started using the [Optional chaining syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#browser_compatibility), which requires Chrome 80+/Firefox 74+. I don't plan on supporting old browsers all the way back. Is there any reason why you are not able to update your browser?

If you need an old browser version for testing compatibility on old browser, I guess the best option would be to use an older version of ModHeader on those browsers. If needed, I can provide the zip file for you to install manually.

**Comment by jockie** [comment]
Well, then some metadata from the version history https://addons.mozilla.org/de/firefox/addon/modheader-firefox/versions/ seems to be wrong. For me it says:
![grafik](https://user-images.githubusercontent.com/6338005/168316665-c4877360-f85e-440c-b4f5-be6ba266a3b4.png)

**Comment by hao1300** [comment]
ah, I think that got automatically added from the manifest file, which I didn't update. I have sent out v4.0.5 to raise the min supported version on Firefox.

**Comment by hao1300** [comment]
By the way, here is the link to download the old archived version of ModHeader 3.x: https://github.com/modheader/modheader/releases/tag/v3.1.27
